apiVersion: v1
kind: Service
metadata:
  name: userportalnpservice-srv
spec:
  type: NodePort
  selector:
    app: userportalservice
  ports:
    - name: userportalservice
      protocol: TCP
      port: 80
      targetPort: 80